---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - mailcow_prepare

- name: install
  ansible.builtin.include_tasks: install.yml
  tags:
    - mailcow_install

- name: configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - mailcow_configure
