---

- name: snapd
  src: bodsch.snapd
  version: 1.2.1

- name: apparmor
  src: bodsch.apparmor
  version: 1.0.2

- name: nginx
  src: bodsch.nginx
  version: 0.12.0

- name: php
  src: bodsch.php
  version: 2.1.1

- name: pecl
  src: https://github.com/bodsch/ansible-php-pecl.git

- name: redis
  src: bodsch.redis
  version: 1.4.0

- name: mariadb
  src: bodsch.mariadb
  version: 2.3.1

...
